import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { homePageFaqs, homepageGuides, homeScenarioInputs } from "../content/home";
import { calculatorCostAssumptions, calculatorMetadata } from "../data/assumptions/calculator";
import { calculateUpfrontCosts } from "../lib/calculator";
import { popularBuyingCostExampleSlugs, priceGuideLinks } from "../lib/price-guide-links";

const pageSource = readFileSync("app/page.tsx", "utf8");
const heroSource = readFileSync("components/Hero.tsx", "utf8");
const guidesSource = readFileSync("content/guides.ts", "utf8");

test("homepage has exactly one approved H1", () => {
  assert.equal((heroSource.match(/<h1\b/g) ?? []).length + (pageSource.match(/<h1\b/g) ?? []).length, 1);
  assert.match(heroSource, /UK House Buying Cost Calculator/);
});

test("calculator appears before editorial sections", () => {
  assert.ok(pageSource.indexOf("<CalculatorForm") < pageSource.indexOf("What the result includes"));
});

test("approved metadata and canonical path are present", () => {
  assert.match(pageSource, /UK House Buying Cost Calculator 2026 \| TrueHomeCosts/);
  assert.match(pageSource, /Calculate the total upfront cost of buying a home in the UK/);
  assert.match(pageSource, /path: "\/"/);
});

test("homepage displays exactly six price examples and links to the hub", () => {
  assert.equal(popularBuyingCostExampleSlugs.length, 6);
  assert.match(pageSource, /View buying costs for all property prices/);
  assert.match(pageSource, /house-buying-cost-by-property-price/);
  assert.equal(priceGuideLinks.length, 16);
});

test("homepage ranges and review details come from central data", () => {
  assert.ok(calculatorCostAssumptions.length >= 8);
  assert.match(pageSource, /calculatorCostAssumptions\.map/);
  assert.equal(calculatorMetadata.dataVersion, "2026.07");
  assert.equal(calculatorMetadata.lastReviewed, "2026-07-19");
});

test("official assumptions have sources and dates and estimates are not official", () => {
  for (const assumption of calculatorCostAssumptions) {
    if (assumption.classification === "official") {
      assert.ok(assumption.sourceName);
      assert.ok(assumption.sourceUrl);
      assert.ok(assumption.lastVerified);
    }
    if (assumption.classification === "estimate") assert.notEqual(assumption.classification, "official");
  }
});

test("worked examples are generated by production calculation functions", () => {
  for (const scenario of homeScenarioInputs) {
    assert.ok(calculateUpfrontCosts(scenario.input).totalUpfrontCash > scenario.input.propertyPrice * 0.1);
  }
});

test("five visible FAQs share the schema source", () => {
  assert.equal(homePageFaqs.length, 5);
  assert.match(pageSource, /faqPageSchema\(homePageFaqs/);
  assert.match(pageSource, /<FAQSection items=\{homePageFaqs/);
});

test("every homepage guide resolves through the existing guide catalogue", () => {
  for (const guide of homepageGuides) assert.match(guidesSource, new RegExp(`slug: "${guide.slug}"`));
});

test("review date drives visible copy and structured data", () => {
  assert.match(pageSource, /calculatorMetadata\.lastReviewedLabel/);
  assert.match(pageSource, /dateModified: calculatorMetadata\.lastReviewed/);
});
